### ISSUE TITLE
More sound memes 

### ISSUE THREAD

**Issue by Frtygmr** [ThzeTerminator/weedbot420issues#3]
**Is this related to an already existing command? If so, which one**
It's pretty similar to xdlaugh or xdfunnymoment

**Describe your idea**
Okay so it plays the bruh sound effect (https://youtu.be/2ZIpFytCSVc) in vc the user is in whenever the respective command is used. The command could be something like "xdbruh" or "xdbruh moment" 

**Describe alternatives you've seen**
Idk

**Additional context**
![images (31)](https://user-images.githubusercontent.com/77645256/104967589-cf50bf80-59f4-11eb-8b08-826780ba0694.jpeg)

**Comment by ThzeTerminator** [comment]
Terrible title jesus

**Comment by ThzeTerminator** [comment]
Issue has been sent to the weedbot repo. If something changes, I will comment on this issue.

Thank you for your suggestion!

**Comment by ThzeTerminator** [comment]
@Frtygmr Post whatever sounds you want to suggest into this issue rather than Discord. Please don't reopen the comment unless 7 days have passed and I've yet to label this issue as completed

**Comment by Frtygmr** [comment]
**Another meme sound effect** 
xdbababooey or a shorter fitting command you see fit (https://youtu.be/U_cPir6MwLM)

**Comment by Frtygmr** [comment]
**Another meme sound effect**
xdfart or again, whatever you see fit (https://youtu.be/MBmb5_TTT-w)

**Comment by ThzeTerminator** [comment]
I will probably revamp sound commands to be in one single command for the sake of organization/optimization.

**Comment by ThzeTerminator** [comment]
I have revamped the sound command, it's only a matter of dropping files in there.

I'm labeling this issue as implemented, but you can still send me shitposts

**Comment by Frtygmr** [comment]
**A compilation of shitpost I've snitched off from a playlist:**
Intro of a certain website 
https://youtu.be/DCmh5fvgqq4
Robert Downey Jr scream
https://youtu.be/RkH-fMg3MGM
Dolphin laugh type beat shit 
https://youtu.be/0nFUq0T1t14
Certain clappery
https://youtu.be/2h_omaXYtMI
h
https://youtu.be/ML5UI-0JS_Q
h2
https://youtu.be/hgvMlGYSCTk
h2O
https://youtu.be/nUxHMDGW0Yw

**Comment by ThzeTerminator** [comment]
should be done

try `{prefix}sound clap`

**Comment by ThzeTerminator** [comment]
New syntax is `{prefix}sound [bababooey | bruh | clap | fart | scream | sienfeld]`
