### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by KnightIsrael** [ThzeTerminator/weedbot420issues#4]
**READ ME FIRST!**
This is obviously a feature request, not a bug report. You should use this to request features or changes on the bot. This is also not a appeal form to be removed from the blacklist/restrictions. Such requests will be closed without further notice, as they're supposed to through dbot@thzeterminator.eu. Futhermore, please make your titles short and to the point! You can remove this part.

**Is this related to an already existing command? If so, which one**
If not; please just write **No**.Otherwise, please avoid using aliasses

**Describe your idea**
A clear and concise description.

**Describe alternatives you've seen**
A clear and concise description.

**Additional context**

add a gacha nsfw feature xd

**Comment by ThzeTerminator** [comment]
Alright, I'm blocking you from the repository and bot.
