### ISSUE TITLE
Your bot glitched

### ISSUE THREAD

**Issue by Fares199873** [ThzeTerminator/weedbot420issues#5]
Hello, I just got blacklisted because of someone was spamming the xdf command, and I just came at the same time to use the xdf command and only when I sent it for once, I got blacklisted automatically, that doesn't make any sense, also the user who spamming xdf here's his tag and username @𝖍1𝖌𝖍 𝖍𝖊𝖆𝖛𝖓#7123 
and here's the message when this happened https://discord.com/channels/152201293757284352/272814335238340608/801811373788758026
![Screenshot_20210121-155256](https://user-images.githubusercontent.com/77790600/105361701-a00f9d80-5c02-11eb-8fd4-4ab25a5622e0.png)

**Comment by ThzeTerminator** [comment]
This repository is for bug reports, not an appeal to be taken off the blacklist. Such requests are closed automatically, as they're supposed to go through dbot@thzeterminator.eu

**Comment by ThzeTerminator** [comment]
@Fares199873 This might've been a mistake, please contact me through dbot@thzeterminator.eu with as subject **<your_discord_name#0000> Blacklist Appeal**
